async function sha256Text(text) {
  const data = new TextEncoder().encode(text);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, "0")).join("");
}

async function evaluateClaim(claim) {
  const artifact = claim.artifact || {};
  const path = artifact.path;
  const expected = (artifact.sha256 || "").toLowerCase();
  const content = claim.simulated_artifact_content;
  const checkedAt = new Date().toISOString();

  if (!path) {
    return {
      verdict: "INADMISSIBLE",
      reason: "claim has no artifact path",
      checked_at: checkedAt
    };
  }

  if (content === null || content === undefined) {
    return {
      verdict: "INADMISSIBLE",
      reason: "no execution artifact exists at claimed path",
      checked_at: checkedAt,
      claimed_path: path,
      claimed_sha256: expected || null,
      actual_sha256: null
    };
  }

  const actual = await sha256Text(content);

  if (!expected) {
    return {
      verdict: "INADMISSIBLE",
      reason: "artifact exists but claim lacks expected hash",
      checked_at: checkedAt,
      claimed_path: path,
      claimed_sha256: null,
      actual_sha256: actual
    };
  }

  if (actual !== expected) {
    return {
      verdict: "REJECTED",
      reason: "artifact hash mismatch; evidence is stale or tampered",
      checked_at: checkedAt,
      claimed_path: path,
      claimed_sha256: expected,
      actual_sha256: actual
    };
  }

  return {
    verdict: "ADMISSIBLE",
    reason: "artifact exists and hash matches claim",
    checked_at: checkedAt,
    claimed_path: path,
    claimed_sha256: expected,
    actual_sha256: actual
  };
}

function verdictClass(verdict) {
  return verdict.toLowerCase();
}

function renderResult(result) {
  return `<pre class="result ${verdictClass(result.verdict)}">${JSON.stringify(result, null, 2)}</pre>`;
}

const FALLBACK_CLAIMS = [
  {
    "title": "Fabricated completion",
    "claim_id": "claim-fabricated-001",
    "agent_claim": "I created the requested report.",
    "artifact": {"path": "missing_report.txt", "sha256": ""},
    "simulated_artifact_content": null
  },
  {
    $1988a44b149d3356663c4905806504b4d82c8d502e1960a5b9f73170378cf9918"},
    "simulated_artifact_content": "Quarterly report generated by the runtime.\n"
  },
  {
    "title": "Tampered / stale completion",
    "claim_id": "claim-stale-001",
    "agent_claim": "I created the requested report.",
    "artifact": {"path": "stale_report.txt", "sha256": "eb40b14f31f101a9e1d245542d0609bad1f14afbec82dbcb0addb271a3e2a23c"},
    "simulated_artifact_content": "Old report content that no longer matches the claim.\n"
  }
];

async function loadClaims() {
  try {
    const response = await fetch("sample_claims.json", {cache: "no-store"});
    if (!response.ok) throw new Error("fetch failed");
    return await response.json();
  } catch (_) {
    // Allows the demo to run directly from file:// in browsers that block local fetch.
    return FALLBACK_CLAIMS;
  }
}

async function render() {
  const claims = await loadClaims();
  const container = document.getElementById("cases");
  container.innerHTML = "";

  for (const claim of claims) {
    const result = await evaluateClaim(claim);
    const card = document.createElement("section");
    card.className = "card";
    card.innerHTML = `
      <div class="case-header">
        <h2>${claim.title}</h2>
        <span class="pill ${verdictClass(result.verdict)}">${result.verdict}</span>
      </div>
      <p class="claim">Agent claim: "${claim.agent_claim}"</p>
      <div class="grid">
        <div>
          <h3>Claimed evidence</h3>
          <pre>${JSON.stringify(claim.artifact, null, 2)}</pre>
        </div>
        <div>
          <h3>Gate verdict</h3>
          ${renderResult(result)}
        </div>
      </div>
    `;
    container.appendChild(card);
  }
}

render().catch(err => {
  document.getElementById("cases").innerHTML = `<pre class="result rejected">${err.stack || err}</pre>`;
});


